version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest


  distributedcache:
    image: redis


  productDB:
    image: postgres

  basketDB:
    image: postgres
  

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: Category/Dockerfile
    depends_on:
      - sqlserver

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products/Dockerfile
    depends_on:
      - productDB

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
      - basketDB

volumes:
  sqlserver_data:
  productDB_data:
  basketDB_data:
