version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"  # if using Express edition
      INIT_SQL: "CREATE DATABASE MicroCategory;"
    ports:
      - "1433:1433"

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    environment:
      - ConnectionStrings__MicroSericeShop=Server=sqlserver;Database=CategoryDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: Category/Dockerfile
    depends_on:
      - sqlserver

