version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest


  postgres:
    image: postgres:latest
  

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: Category/Dockerfile
    depends_on:
      - sqlserver

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products/Dockerfile
    depends_on:
      - postgres

volumes:
  sqlserver_data:
  postgres_data: